/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CallRouteImport } from './routes/call'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MotivationRouteImport } from './routes/motivation'
import { Route as PowerdialerRouteImport } from './routes/powerdialer'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as PowerdialerCallRouteImport } from './routes/powerdialer.call'
import { Route as PowerdialerExportRouteImport } from './routes/powerdialer.export'
import { Route as PowerdialerImportRouteImport } from './routes/powerdialer.import'
import { Route as PowerdialerLogRouteImport } from './routes/powerdialer.log'
import { Route as PowerdialerQueueRouteImport } from './routes/powerdialer.queue'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CallRoute = CallRouteImport.update({
  id: '/call',
  path: '/call',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MotivationRoute = MotivationRouteImport.update({
  id: '/motivation',
  path: '/motivation',
  getParentRoute: () => rootRouteImport,
} as any)
const PowerdialerRoute = PowerdialerRouteImport.update({
  id: '/powerdialer',
  path: '/powerdialer',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const PowerdialerCallRoute = PowerdialerCallRouteImport.update({
  id: '/call',
  path: '/call',
  getParentRoute: () => PowerdialerRoute,
} as any)
const PowerdialerExportRoute = PowerdialerExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => PowerdialerRoute,
} as any)
const PowerdialerImportRoute = PowerdialerImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => PowerdialerRoute,
} as any)
const PowerdialerLogRoute = PowerdialerLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => PowerdialerRoute,
} as any)
const PowerdialerQueueRoute = PowerdialerQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => PowerdialerRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/call': typeof CallRoute
  '/features': typeof FeaturesRoute
  '/mcp': typeof McpRoute
  '/motivation': typeof MotivationRoute
  '/powerdialer': typeof PowerdialerRouteWithChildren
  '/queue': typeof QueueRoute
  '/settings': typeof SettingsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/powerdialer/call': typeof PowerdialerCallRoute
  '/powerdialer/export': typeof PowerdialerExportRoute
  '/powerdialer/import': typeof PowerdialerImportRoute
  '/powerdialer/log': typeof PowerdialerLogRoute
  '/powerdialer/queue': typeof PowerdialerQueueRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/call': typeof CallRoute
  '/features': typeof FeaturesRoute
  '/mcp': typeof McpRoute
  '/motivation': typeof MotivationRoute
  '/powerdialer': typeof PowerdialerRouteWithChildren
  '/queue': typeof QueueRoute
  '/settings': typeof SettingsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/powerdialer/call': typeof PowerdialerCallRoute
  '/powerdialer/export': typeof PowerdialerExportRoute
  '/powerdialer/import': typeof PowerdialerImportRoute
  '/powerdialer/log': typeof PowerdialerLogRoute
  '/powerdialer/queue': typeof PowerdialerQueueRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/call': typeof CallRoute
  '/features': typeof FeaturesRoute
  '/mcp': typeof McpRoute
  '/motivation': typeof MotivationRoute
  '/powerdialer': typeof PowerdialerRouteWithChildren
  '/queue': typeof QueueRoute
  '/settings': typeof SettingsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/powerdialer/call': typeof PowerdialerCallRoute
  '/powerdialer/export': typeof PowerdialerExportRoute
  '/powerdialer/import': typeof PowerdialerImportRoute
  '/powerdialer/log': typeof PowerdialerLogRoute
  '/powerdialer/queue': typeof PowerdialerQueueRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/call'
    | '/features'
    | '/mcp'
    | '/motivation'
    | '/powerdialer'
    | '/queue'
    | '/settings'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/powerdialer/call'
    | '/powerdialer/export'
    | '/powerdialer/import'
    | '/powerdialer/log'
    | '/powerdialer/queue'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/call'
    | '/features'
    | '/mcp'
    | '/motivation'
    | '/powerdialer'
    | '/queue'
    | '/settings'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/powerdialer/call'
    | '/powerdialer/export'
    | '/powerdialer/import'
    | '/powerdialer/log'
    | '/powerdialer/queue'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/call'
    | '/features'
    | '/mcp'
    | '/motivation'
    | '/powerdialer'
    | '/queue'
    | '/settings'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/powerdialer/call'
    | '/powerdialer/export'
    | '/powerdialer/import'
    | '/powerdialer/log'
    | '/powerdialer/queue'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CallRoute: typeof CallRoute
  FeaturesRoute: typeof FeaturesRoute
  McpRoute: typeof McpRoute
  MotivationRoute: typeof MotivationRoute
  PowerdialerRoute: typeof PowerdialerRouteWithChildren
  QueueRoute: typeof QueueRoute
  SettingsRoute: typeof SettingsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call': {
      id: '/call'
      path: '/call'
      fullPath: '/call'
      preLoaderRoute: typeof CallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motivation': {
      id: '/motivation'
      path: '/motivation'
      fullPath: '/motivation'
      preLoaderRoute: typeof MotivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/powerdialer': {
      id: '/powerdialer'
      path: '/powerdialer'
      fullPath: '/powerdialer'
      preLoaderRoute: typeof PowerdialerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/powerdialer/call': {
      id: '/powerdialer/call'
      path: '/call'
      fullPath: '/powerdialer/call'
      preLoaderRoute: typeof PowerdialerCallRouteImport
      parentRoute: typeof PowerdialerRoute
    }
    '/powerdialer/export': {
      id: '/powerdialer/export'
      path: '/export'
      fullPath: '/powerdialer/export'
      preLoaderRoute: typeof PowerdialerExportRouteImport
      parentRoute: typeof PowerdialerRoute
    }
    '/powerdialer/import': {
      id: '/powerdialer/import'
      path: '/import'
      fullPath: '/powerdialer/import'
      preLoaderRoute: typeof PowerdialerImportRouteImport
      parentRoute: typeof PowerdialerRoute
    }
    '/powerdialer/log': {
      id: '/powerdialer/log'
      path: '/log'
      fullPath: '/powerdialer/log'
      preLoaderRoute: typeof PowerdialerLogRouteImport
      parentRoute: typeof PowerdialerRoute
    }
    '/powerdialer/queue': {
      id: '/powerdialer/queue'
      path: '/queue'
      fullPath: '/powerdialer/queue'
      preLoaderRoute: typeof PowerdialerQueueRouteImport
      parentRoute: typeof PowerdialerRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PowerdialerRouteChildren {
  PowerdialerCallRoute: typeof PowerdialerCallRoute
  PowerdialerExportRoute: typeof PowerdialerExportRoute
  PowerdialerImportRoute: typeof PowerdialerImportRoute
  PowerdialerLogRoute: typeof PowerdialerLogRoute
  PowerdialerQueueRoute: typeof PowerdialerQueueRoute
}

const PowerdialerRouteChildren: PowerdialerRouteChildren = {
  PowerdialerCallRoute: PowerdialerCallRoute,
  PowerdialerExportRoute: PowerdialerExportRoute,
  PowerdialerImportRoute: PowerdialerImportRoute,
  PowerdialerLogRoute: PowerdialerLogRoute,
  PowerdialerQueueRoute: PowerdialerQueueRoute,
}

const PowerdialerRouteWithChildren = PowerdialerRoute._addFileChildren(
  PowerdialerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CallRoute: CallRoute,
  FeaturesRoute: FeaturesRoute,
  McpRoute: McpRoute,
  MotivationRoute: MotivationRoute,
  PowerdialerRoute: PowerdialerRouteWithChildren,
  QueueRoute: QueueRoute,
  SettingsRoute: SettingsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
